export const BUILD_VERSION_NUMBER = "1.0.0"
export const BUILD_DEPLOY_NUMBER = "70"
export const BUILD_COMMIT = "plainlang070612"

export const BUILD_LABEL = `${BUILD_VERSION_NUMBER}-${BUILD_DEPLOY_NUMBER}-${BUILD_COMMIT}`

export const BUILD_VERSION = BUILD_LABEL
